### ISSUE TITLE
`Save` keyword does not work in Python 3

### ISSUE THREAD

**Issue by bartkl** [bartkl/robotframework-excellentlibrary#1]
When calling `Save`, the following exception occurs:

```python
AttributeError: 'dict' object has no attribute 'iteritems' 
```

**Comment by bartkl** [comment]
This is a known Python 2/3 difference: `iteritems` is specific to the former, while in the latter this has been renamed to `tems`.

**Comment by cbos-immune** [comment]
I cannot reproduce this issue. On my configuration (Python 3.7.2.) it works.

**Comment by cbos-immune** [comment]
I can confirm that this isn't a issue on Python 3.
I have tested this on 3 seperate divices, using the packages and versions below:

- Python 3.7.2.
- openpyxl 2.5.8.
- robot framework 3.1.1

**Comment by bartkl** [comment]
Okay, that sounds like sufficient evidence to me to close this issue. Thanks @christian-bos for testing!
