### ISSUE TITLE
Macro-enabled workbook corrupts when saving more than once

### ISSUE THREAD

**Issue by MichielYKamp** [bartkl/robotframework-excellentlibrary#16]
Take a look at issue:
[https://bitbucket.org/openpyxl/openpyxl/issues/861/cannot-save-a-file-with-comments-twice](https://bitbucket.org/openpyxl/openpyxl/issues/861/cannot-save-a-file-with-comments-twice)

This is a known problem in openpyxl for which there seems to be no fix.
There is a workaround mentioned, however.

Might it be a good idea to implement this workaround in the keyword 'save' of this library, or maybe make a new (temporary) save keyword to use until this is properly fixed in openpyxl?

**Reproduce**
You can easily reproduce this issue by creating a macro-enabled workbook (there need not actually be macros in it) and adding a comment to one of the cells.
If you then call "open workbook", "save" and "save" with the library and then open it manually, you will get a message that the file has been corrupted.

**Comment by bartkl** [comment]
Hey Michiel,

Interesting. I am indeed capable of reproducing the error mentioned in the OpenPyXL issue you refer to (specifically: `AttributeError: 'NoneType' object has no attribute 'read'`), and when manually opening the workbook I'm also told it's corrupt.

In the process however I noticed another, related bug: when I create a macro-enabled workbook, open it using ExcellentLibrary with the parameter `keep_vba=True`, then `Save` it and finally open it manually, it also gives me the corruption message.

I will look into this, thanks.

Bart

**Comment by bartkl** [comment]
Just implemented my idea in a separate branch. Tested it quickly and it seems to work just fine. Please check out the pull request if you agree with this solution.

**Comment by MichielYKamp** [comment]
Een pull request is een merge request?
Lijkt dat ik dat niet kan, ik zie deze melding "Only those with write access to this repository can merge pull requests."

**Comment by bartkl** [comment]
No problem, I merged it just now.
