### ISSUE TITLE
Installing the library with pip on Python 3 produces an error

### ISSUE THREAD

**Issue by cbos-immune** [bartkl/robotframework-excellentlibrary#18]
Could not find a version that satisfies the requirement robotframework-excellentlibrary (from versions: )
No matching distribution found for robotframework-excellentlibrary

**Comment by bartkl** [comment]
Hello Christian,

The PyPI release has been restricted to Python 2.7.x:

```python
    python_requires="~=2.7",
```

I haven't yet tried the library with Python 3, but there is an open issue regarding it: #1. You can try running it yourself by getting the code from GitHub rather than PyPI, and look whether you'll run into the saving issue or not. Who knows you could even fix it ;).


Greetings,
Bart

**Comment by bartkl** [comment]
Okay, so you're saying #1 is a non-issue and can be closed?
Also, if you tested the library properly with Python 3 and everything work's fine, please let me know, because then we can remove the restriction mentioned above.

**Comment by cbos-immune** [comment]
As far as I can see, #1 isn't an issue (any more).

**Comment by Srihari88** [comment]
@cbos-immune Unable to install the excellentlibrary below is the issue.

Collecting robotframework-excellentlibrary

  Could not find a version that satisfies the requirement robotframework-excellentlibrary (from versions: )
No matching distribution found for robotframework-excellentlibrary


Using python version: 3.7
Operating System: OSX

**Comment by e-peters-waternet** [comment]
> Also, if you tested the library properly with Python 3 and everything work's fine, please let me know, because then we can remove the restriction mentioned above.

Not everything works fine, e.g. #20 
Fixed that one in my own fork. However, this will introduce some backward incompatabilities when still using python 2.x. Imho we should move on... Python 2 will be EOL anyway as per January 2020.

**Comment by bartkl** [comment]
The newest release (v1.0.0) now supports Python 3. Note that compatibility with Python 2 has been sacrificed in the process.
