### ISSUE TITLE
Add support for the older Excel xls file type

### ISSUE THREAD

**Issue by bartkl** [bartkl/robotframework-excellentlibrary#2]
Currently `OpenPyXL` supports only Excel 2010 files (and beyond). It would be nice if older Excel files would be supported as well. Since `OpenPyXL` does not support this, another Python library would be needed to achieve this.

**Comment by MichielYKamp** [comment]
I am not sure we should have to support files older than Excel 2010. I believe even Excel 2010 itself is (soon) not supported anymore.

**Comment by bartkl** [comment]
I think you're right. I'm going to close this issue.
