### ISSUE TITLE
'Read sheet data' raises error because Python 3 no longer has dict.itervalues()

### ISSUE THREAD

**Issue by e-peters** [bartkl/robotframework-excellentlibrary#20]
Python 2/3 issue. I'm using Python 3.7.2.
When reading data from an xlsx using keyword _Read sheet data_ an error is raised on execution of the RFW test case:
`AttributeError: 'dict' object has no attribute 'itervalues'`

Reason: 'itervalues' is no longer available in Python 3, as stated [here](https://wiki.python.org/moin/Python3.0#Built-In_Changes):
> Remove dict.iteritems(), dict.iterkeys(), and dict.itervalues().
> Instead: use dict.items(), dict.keys(), and dict.values() respectively.

Both 'iteritems' and 'itervalues' are used in the excellentlibrary, albeit only once.

**Comment by e-peters-waternet** [comment]
I tested with my own (forked) version of the ExcellentLibrary, including the abovementioned changes (remove the 'iter'-part).
I was able to open an xlsx file without any errors being raised!

Python version used: 3.7.4

**Comment by bartkl** [comment]
The newest release (v1.0.0) now supports Python 3. Note that compatibility with Python 2 has been sacrificed in the process.
